version: '3.8'
services:
  graphdb:
    restart: always
    image: neo4j:4.2.3
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./.data_storage/neo4j:/data
    environment:
      - NEO4J_AUTH
